from __future__ import annotations

from typing import Any

def get_sheet_data(path: str, sheet: int) -> list[list[Any]]: ...
def get_sheet_names(path: str) -> list[str]: ...

class CalamineError(Exception): ...
