# some code from https://github.com/pydantic/pydantic-core/blob/d6e7890b36ef21cb28180a7f5b1479da2319012d/.github/workflows/ci.yml
# MIT License, see author list by link

name: CI

on:
  push:
    branches:
      - main
    tags:
      - "**"
  pull_request: {}

permissions: {}

jobs:
  test:
    name: test ${{ matrix.python-version }} pandas ${{ matrix.pandas-version }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
        pandas-version:
          - "2.3.*"
          - "3.0.*"
        include:
          # https://github.com/pandas-dev/pandas/issues/42509
          - python-version: "pypy3.11"
            pandas-version: "none"
          - python-version: "3.14t"
            pandas-version: "3.0.*"
        exclude:
          - python-version: "3.10"
            pandas-version: "3.0.*"

    runs-on: ubuntu-latest

    env:
      PYTHON: ${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: install rust stable
        uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable
        with:
          toolchain: stable

      - id: cache-rust
        name: cache rust
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          key: v3

      - name: set up python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true

      - id: cache-py
        name: cache python
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ${{ env.pythonLocation }}
          key: >
            py
            ${{ runner.os }}
            ${{ matrix.python-version }}
            ${{ matrix.pandas-version }}

      - run: |
          if [ ${{ matrix.pandas-version }} == 'none' ]; then
            pip install pytest
          else
            pip install pytest pandas[excel]==${{ matrix.pandas-version }}
          fi
        if: steps.cache-py.outputs.cache-hit != 'true'

      - run: pip install -e .
        env:
          RUST_BACKTRACE: 1

      - run: pip freeze

      - run: pytest

  lint:
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: install rust stable
        uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable
        with:
          components: rustfmt, clippy

      - name: cache rust
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.14"

      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        id: cache-py
        name: cache python
        with:
          path: ${{ env.pythonLocation }}
          key: >
            py
            ${{ env.pythonLocation }}

      - run: pip install pre-commit mypy
        if: steps.cache-py.outputs.cache-hit != 'true'

      - run: pip install .
        if: steps.cache-py.outputs.cache-hit != 'true'

      - run: pip freeze

      - run: pre-commit run --all-files

  # https://github.com/marketplace/actions/alls-green#why used for branch protection checks
  check:
    if: always()
    needs: [test, lint]
    runs-on: ubuntu-latest
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}

  build:
    name: build on ${{ matrix.os }} (${{ matrix.target }} - ${{ matrix.interpreter || 'all' }}${{ matrix.os == 'linux' && format(' - {0}', matrix.manylinux == 'auto' && 'manylinux' || matrix.manylinux) || '' }})
    permissions:
      contents: read
    if: success()
    strategy:
      fail-fast: false
      matrix:
        os: [linux, macos, windows]
        target: [undefined]
        manylinux: [auto]
        include:
          # manylinux for various platforms
          - os: linux
            manylinux: auto
            target: x86_64
          - os: linux
            manylinux: auto
            target: aarch64
          - os: linux
            manylinux: auto
            target: i686
          - os: linux
            manylinux: auto
            target: armv7
            interpreter: 3.10 3.11 3.12 3.13 3.14 3.14t
          - os: linux
            manylinux: auto
            target: ppc64le
            interpreter: 3.10 3.11 3.12 3.13 3.14 3.14t
          - os: linux
            manylinux: auto
            target: s390x
            interpreter: 3.10 3.11 3.12 3.13 3.14 3.14t

          # musllinux
          - os: linux
            manylinux: musllinux_1_1
            target: x86_64
          - os: linux
            manylinux: musllinux_1_1
            target: aarch64
          - os: linux
            manylinux: musllinux_1_1
            target: armv7

          # macos
          - os: macos
            target: x86_64
          - os: macos
            target: aarch64

          # windows
          - os: windows
            target: x86_64
            interpreter: 3.10 3.11 3.12 3.13 3.14 3.14t
          - os: windows
            target: i686
            interpreter: 3.10 3.11 3.12 3.13 3.14
          - os: windows
            target: aarch64
            runs-on: windows-11-arm
            interpreter: 3.11 3.12 3.13 3.14 3.14t

        exclude:
          # was just a dummy variable to set a default value for target
          - target: undefined

    runs-on: ${{ matrix.runs-on || format('{0}-latest', (matrix.os == 'linux' && 'ubuntu') || matrix.os) }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: set up python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.14"

      - name: install rust stable
        uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable

      - run: pip install -U twine

      - name: build sdist
        if: ${{ matrix.os == 'linux' && matrix.target == 'x86_64' && matrix.manylinux == 'auto' }}
        uses: PyO3/maturin-action@e83996d129638aa358a18fbd1dfb82f0b0fb5d3b # v1.51.0
        with:
          command: sdist
          args: --out dist
          rust-toolchain: stable

      - name: build wheels
        uses: PyO3/maturin-action@e83996d129638aa358a18fbd1dfb82f0b0fb5d3b # v1.51.0
        with:
          target: ${{ matrix.target }}
          manylinux: ${{ matrix.manylinux || 'auto' }}
          args: --release --out dist --interpreter ${{ matrix.interpreter || '3.10 3.11 3.12 3.13 3.14 3.14t pypy3.11' }}
          rust-toolchain: stable

      - run: ${{ (matrix.os == 'windows' && 'dir') || 'ls -lh' }} dist/

      - run: twine check --strict dist/*

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: wheels-${{ matrix.os }}-${{ matrix.target }}-${{ matrix.manylinux || 'auto' }}
          path: dist

  release:
    needs: [build, check]
    if: success() && startsWith(github.ref, 'refs/tags/')

    runs-on: ubuntu-latest

    environment:
      name: release
      url: https://pypi.org/p/python-calamine/

    permissions:
      id-token: write

    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: dist
          pattern: wheels-*
          merge-multiple: true

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # release/v1.14

  gh-release:
    needs: [build, check]
    if: success() && startsWith(github.ref, 'refs/tags/')

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: dist
          pattern: wheels-*
          merge-multiple: true

      - name: Upload to GitHub
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3.0.0
        with:
          generate_release_notes: true
          files: |
            dist/*
